### ISSUE TITLE
[Request] - Format labels for different languages

### ISSUE THREAD

**Issue by TommiSvard** [WebDataRocks/pivot-angular#13]
Hello, first of all i would like to thank you for an truly incredible library!

I have an request regarding the labels, when they are rendered in a different language where the names of functions and such may be longer it cuts the word off. I've only played around with it in devtools but it seems that one fix could be to just increase the width for the **li** like : 

#wdr-toolbar-wrapper #wdr-toolbar li {
    display: inline-block;
    background: 0 0;
    vertical-align: top;
    padding: 0;
    position: relative;
    width: 100px; /* increased from 57px */ 
}

However, it seems like the first item (menu_connect) doesnt get aligned with the table and i dont know if this breaks any other layout. 

Would it also be possible to change the line-height for the labels? As of now the style looks like: 

#wdr-toolbar-wrapper #wdr-toolbar>.wdr-toolbar-group-right>li>a span, #wdr-toolbar-wrapper #wdr-toolbar>li>a span {
    position: absolute;
    top: 55px;
    line-height: 12px;
    left: 0;
    right: 0;
}

But with the current line-height it becomes a problem with umaluts, an example is the Open button where in swedish it's "Öppna" and in german "Öffnen" but with the current line-height the dots get hidden and becomes "Oppna" and "Offnen". 

Thanks in advance!

**Comment by TommiSvard** [comment]
When the morning coffe kicked in a realised i could just implement the needed styles myself? 

However, thank you for the library :)

**Comment by pechurkam** [comment]
Hi @TommiSvard!

Thank you for your kind words about our component. We are glad that you are satisfied with it.

Speaking of your questions:
Indeed, you can add any styles to WebDataRocks, customizing it to your needs. This kind of customization could be achieved by adding a new CSS file to your project and overriding the component styles using `!important`.

Hope it helps!

Regards,
Milena
