### ISSUE TITLE
I Am Using Angular 8 Along With Webdatarocks, How To Call Or Read  REST API (JSON) With Basic Authorization.

### ISSUE THREAD

**Issue by rajeevrin** [WebDataRocks/pivot-angular#3]
Hi Webdatarocks Team,
I am using Angular 8 along with webdatarocks, how to call or Read  REST API (JSON) with Basic Authorization.
Also when I am trying to upload Local JSON I am getting error JSON data is invalid.
I am stuck here please help me.
Regards,
Rajeev

**Comment by mhalaida** [comment]
Hi @rajeevrin,

Thank you for writing to us.

Please see our response in the corresponding forum thread: https://www.webdatarocks.com/question/i-am-using-angular-8-along-with-webdatarocks-how-to-call-post-method-rest-api-with-basic-auth/

Best regards,
Mykhailo
