### ISSUE TITLE
Does not work if the data size is a little large!

### ISSUE THREAD

**Issue by brahim-slimani** [WebDataRocks/pivot-angular#45]
Trying to populate a CSV data that exceed some 90kb, it throws an error then the data are not rendered! 
See the snapshot below,

![image](https://github.com/WebDataRocks/pivot-angular/assets/36894964/9685196e-58d0-4281-8806-fe3bd2261186)

Is there any workaround for this issue please!

**Comment by se7enteenblue** [comment]
Hello,

Thank you for the question.

Kindly note that WebDataRocks is designed to visualize only 1MB of data.
For data more than 1MB, we recommend considering using a more advanced pivot table – [Flexmonster](https://www.flexmonster.com/). It’s developed by the same team but doesn’t have such limitations.

Kind regards,
Nadia

**Comment by brahim-slimani** [comment]
> Hello,
> 
> Thank you for the question.
> 
> Kindly note that WebDataRocks is designed to visualize only 1MB of data. For data more than 1MB, we recommend considering using a more advanced pivot table – [Flexmonster](https://www.flexmonster.com/). It’s developed by the same team but doesn’t have such limitations.
> 
> Kind regards, Nadia

Thnx @se7enteenblue for your reply. Indeed, fully agree that the limited size is 1MB, the issue in occurrence is that the data set is bit fewer than 100KB :)
